apiVersion: batch/v1
kind: Job
metadata:
  name: dig
spec:
  template:
    spec:
      containers:
        - name: dig
          image: anubhavmishra/tiny-tools
          command: ['dig', 'static-server.service.dc-east.consul']
      restartPolicy: Never
  backoffLimit: 5